Fix ERROR in gdb.rocm/step-over-kernel-exit.exp
I ran into the following:

ERROR: couldn't compile regular expression pattern: parentheses () not balanced
    while executing
"expect {
-i exp9 -timeout 10
        -re ".*A problem internal to GDB has been detected" {
            fail "$message (GDB internal error)"
            gdb_internal_error..."
    ("uplevel" body line 1)
    invoked from within
"uplevel $body" REGEXP REG_EPAREN {parentheses () not balanced} couldn't compile regular expression pattern: parentheses () not balanced

Looks like we need extra escaping of the brackets when we have some parenthesis
going on.

(cherry picked from commit b6b5a2852b31ae79de3c7102141bdbadea8d475b)
Change-Id: I6c8029c4d21dc1f6b068c74dc5535e54ea1517d4