gdb/amd-dbgapi-target: fix compilation error on gcc 16
GCC 16 and up emit deprecation warnings when performing a bitwise operation
between different enum types. Since ROCgdb builds with -Werror, compilation
fails in amd-dbgapi-target.c :

  ../../gdb/amd-dbgapi-target.c:4656:26: error: bitwise operation between different enumeration types
   'amd_dbgapi_dispatch_barrier_t' and 'amd_dbgapi_dispatch_fence_scope_t' is deprecated
  [-Werror=deprecated-enum-enum-conversion]
   4656 |             if ((barrier | acquire) && release)
        |                  ~~~~~~~^~~~~~~~~~

This commit fixes the compilation error by replacing the bitwise OR with a
logical OR (`||`). The intent behind the operation is checking whether
`barrier` or `acquire` have any flags set. The logical OR operation thus is the
most appropriate.