Fix small buglet in gdb.rocm/instruction-stepping-commands.exp
Currently, we're incorrectly issuing another stepi/nexti even when we
detected too many steps already.  As a consequence, if we do hit the
limit, we're getting:

 FAIL: gdb.rocm/instruction-stepping-commands.exp: stepi: stepi (too many steps)
 FAIL: gdb.rocm/instruction-stepping-commands.exp: nexti: info breakpoints (got interactive prompt)
 ERROR: breakpoints not deleted
 FAIL: gdb.rocm/instruction-stepping-commands.exp: nexti: nexti (too many steps)

This commit makes us not issue that extra step, and so if we hit the
limit, we'll get the intended FAILs, only:

 FAIL: gdb.rocm/instruction-stepping-commands.exp: stepi: stepi (too many steps)
 FAIL: gdb.rocm/instruction-stepping-commands.exp: nexti: nexti (too many steps)

Change-Id: If4100fb1bcfdece529b884c6dc82666e4e2822c0
(cherry picked from commit 0e61e6e43af2c6e9f2b9b9e7c2f607282b12322c)