gdb/python: prevent conversion from pointer to bool in to_python()
While converting some Python code to use new "safety" APIs I realized
that calling to_python() with a pointer like (for example):

   to_python (symtab->compunit ().objfile ())

calls to_python(bool) which is unlikely to be what the user wants.
This commit changes the code to make it a compile-time error.

After trying several approaches, the least intrusive seemed to be
handling bool specially in to_python() template for integral types and
removing to_python(bool) altogether. This way, the above example fails
with:

    error: no matching function for call to ‘to_python(objfile*)’

Tested on x86_64-linux.

Approved-By: Tom Tromey <tom@tromey.com>