gdb/dwarf: fix build error with older gcc
With gcc 7.5.0, we get:

      CXX    dwarf2/read.o
    /home/simark/src/binutils-gdb/gdb/dwarf2/read.c: In function ‘void decode_line_header_for_cu(die_info*, dwarf2_cu*, const file_and_directory&)’:
    /home/simark/src/binutils-gdb/gdb/dwarf2/read.c:5796:25: error: unused variable ‘_’ [-Werror=unused-variable]
           auto [_, inserted_]
                             ^

That version of gcc (and earlier) apparently produces unused variable
warnings for unused structured bindings.  Fix it by accessing `.second`
directly to get the "inserted" boolean value.

Change-Id: I6e78c8c317623f3d830fef8d043f85ff789133d4
Bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81767