gdb.rocm/ocp_mx.exp: Fix pattern matching for invocation error
On SLES-15, gdb.rocm/ocp_mx.exp fails with:

    p $_mx_get_scaled_float(e2m1n, e8m0, 5)
    Python Exception <class 'TypeError'>: invoke() takes from 2 to 3 positional arguments but 4 were given
    Error occurred in Python: invoke() takes from 2 to 3 positional arguments but 4 were given
    (gdb) FAIL: gdb.rocm/ocp_mx.exp: scalefunc_checks: p $_mx_get_scaled_float(e2m1n, e8m0, 5)
    p $_mx_get_scaled_float()
    Python Exception <class 'TypeError'>: invoke() missing 1 required positional argument: 'mxvar'
    Error occurred in Python: invoke() missing 1 required positional argument: 'mxvar'
    (gdb) FAIL: gdb.rocm/ocp_mx.exp: scalefunc_checks: p $_mx_get_scaled_float()

On passing systems, the error message shows

    Error occurred in Python: _MxGetScaledFloat.invoke()

while on failing systems, we see

    Error occurred in Python: invoke()

That is, the class name is not shown.

This patch adjusts the testcase to accept both form, i.e. have an
optional class-name and a dot, then "invoke()".

Bug: SWDEV-526728
Co-authored-by: Olu Ogunbowale <Olu.Ogunbowale@amd.com>
Change-Id: I7fe10b45ceffff862befdade6bf32a932a2cdf2c
(cherry picked from commit b93013cbca65a6a10e3b8849fc8d2d92244122a5)