Fix building GBD with libatomic
GDB currently fails to build with LLVM, following the following upstream
commit:

    commit 329a53a6d590e2e90f590c89473990040a86c8e0
    Date:   Sat Nov 22 11:03:57 2025 -0700

        Some cleanups to "pretend language" handling

Here is the link error:

    /usr/bin/ld: dwarf2/read.o: in function `bool std::__atomic_impl::__compare_exchange<false, packed<dwarf_source_language, 2ul> >(packed<dwarf_source_language, 2ul>&, std::remove_volatile<packed<dwarf_source_language, 2ul> >::type&, std::remove_volatile<packed<dwarf_source_language, 2ul> >::type&, bool, std::memory_order, std::memory_order)':
    /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/atomic_base.h:1002:(.text._ZNSt6atomicI6packedI21dwarf_source_languageLm2EEE23compare_exchange_strongERS2_S2_St12memory_orderS5_[_ZNSt6atomicI6packedI21dwarf_source_languageLm2EEE23compare_exchange_strongERS2_S2_St12memory_orderS5_]+0x1b4): undefined reference to `__atomic_compare_exchange'

This patch proposes a GDB configure update to detect if such flag is
needed.

Change-Id: I5b9fd69a08324dc60b089a440c498d4d803abb68