gdb: Fix build for aarch64-windows
When reload_context was removed from windows_thread_info, it
was missed at one point in aarch64-windows-nat.c:

../../gdb/aarch64-windows-nat.c:260:20: error: no member named 'reload_context' in 'windows_nat::windows_thread_info'
  260 |   gdb_assert (!th->reload_context);
      |                ~~  ^

This removes it.

Approved-By: Tom Tromey <tom@tromey.com>