gdb, gdbserver: create the dependency directories from the Makefiles
Some .deps directories are created at configure time:

 - gdb/configure.ac and gdbserver/configure.ac call ZW_CREATE_DEPDIR,
   which creates the top-level one from config.status.

 - gdbserver/configure.ac has an additional AC_CONFIG_COMMANDS to create
   the .deps dirs for its subdirectories listed in CONFIG_SRC_SUBDIR
   (arch, gdbsupport, nat and target).

Meanwhile, gdb creates the sub-directory ones from the Makefile, through an
order-only prerequisite on the rule for compiling .c files.

If the user deletes a .deps directory created by configure
(config.status, really), then the build breaks:

    $ rm -rf gdb/.deps
    $ make
      CXX    gdb.o
    gdb.c:39:1: fatal error: opening dependency file ./.deps/gdb.Tpo: No such file or directory

On the other hand, it works for those .deps created by a Makefile (they
are re-created as needed).

This patch changes how we create .deps directories to make it simpler,
more robust and consistent.

In both gdb and gdbserver:

 - Add an ALL_DEPDIRS variable, listing the .deps directories, and a
   rule to create them.

 - Make ALL_DEPDIRS an order-only prerequisite of $(all_object_files),
   such that the .deps directories will be created before compiling any
   .o file.

 - Following the rule "things created by make are removed by the clean
   target" and "things created by configure are removed by the distclean
   target", make the clean targets remove the dependency directories.  I
   opted for an `rm -f` followed by a loop of `rmdir` instead of just
   one `rm -rf $(ALL_DEPDIRS)`.  If someone or something messes up
   $ALL_DEPDIRS in the future, there is less chances of things going
   catastrophically wrong.

Note that this changes the command to create directories from "$(SHELL)
$(srcdir)/../install-sh -d" to "mkdir -p".  If there is a reason to use
install-sh to create directories in the build directory, I think it
should be documented, otherwise it just looks strange.

The configure-time creation is not needed anymore.  Replace the
ZW_CREATE_DEPDIR calls with AM_SET_DEPDIR, which is what actually
provides DEPDIR, and drop gdbserver's gdbdepdir AC_CONFIG_COMMANDS.

That leaves gdbserver's CONFIG_SRC_SUBDIR with no user in configure, so
define it directly in gdbserver/Makefile.in, like gdb already does.

Change-Id: I71e76a9a37a525f58c9c66e5556e8da965cc2ca3