gdb, testsuite: fix 'no such variable' error in gdb.rocm/hip-catch-errors.exp
Running gdb.rocm/hip-catch-errors.exp in an environment where the
__hipOnError symbol is not defined gives

  ERROR: tcl error sourcing <path-to>/gdb/testsuite/gdb.rocm/hip-catch-errors.exp.
  ERROR: can't read "res": no such variable
      while executing
  "return $res"
      ("uplevel" body line 27)
        invoked from within
  "uplevel 1 $body"
      invoked from within
  "with_test_prefix preparation_test {
      with_rocm_gpu_lock {
          clean_restart ${::testfile}.dbg
          if {![runto_main]} {
            return false
          }
          gdb_test_mul..."

Fix this by defining "res" at an earlier point.

The problem here is in fact deeper.  The code body that is used in
preparation_test has return statements.  One would expect the return
statements to actually return from preparation_test early and not even
reach `return $res`, but that's not happening because of how
with_rocm_gpu_lock and with_lock are defined and use Tcl's uplevel.
Fixing them will be more involved and should be addressed separately.

(cherry picked from commit 3a93be609785b110a7c2fb7d74c0b306c78a24c0)