[testsuite] Fix ERROR in gdb.rocm/step-over-kernel-exit.exp
I ran into the following:

ERROR: couldn't compile regular expression pattern: parentheses () not balanced
    while executing
"expect {
-i exp9 -timeout 10
        -re ".*A problem internal to GDB has been detected" {
            fail "$message (GDB internal error)"
            gdb_internal_error..."
    ("uplevel" body line 1)
    invoked from within
"uplevel $body" REGEXP REG_EPAREN {parentheses () not balanced} couldn't compile regular expression pattern: parentheses () not balanced

Looks like we need extra escaping of the brackets when we have some parenthesis
going on.