gdb: add check for stale build generated files
Before this series, building gdb generates a file called cp-name-parser.c,
from cp-name-parser.y.  After this series, cp-name-parser.c is a source
file written by hand checked in git.  When doing out of tree builds, a
leftover generated cp-name-parser.c in the build directory would interfere
with the build.  To make "cp-name-parser.o", it will prefer the stale
cp-name-parser.c from the build directory rather than the good
cp-name-parser.c from the source directory.  Debugging the build failure
that arises from this can be difficult and time consuming, especially if
you have never hit the problem before.

I propose to add a check in the Makefile to point out if there exists a
file in the build directory that is known to be stale and that could
interfere with the build.

The alternative is obviously to avoid naming the new file
"cp-name-parser.c", but I don't want to avoid using a good and logical
file name just because of that.

The check looks like this when it catches something:

    Error: stale generated files found in the build directory:
        cp-name-parser.c
    They are left over from an older build of GDB and shadow the
    source files with the same name.  Run "make clean" (or delete
    them manually) then build again.

I made "make clean" remove those files, because why not, it seems
convenient.

The check and removal in "make clean" only happen when the source directory
is different from the build directory.  For in-tree builds, a stale
generated cp-name-parser.c file would presumably prevent checking out a git
commit that has a tracked cp-name-parser.c file.

This patch only adds the machinery, the following patch adds
cp-name-parser.c to the STALE_GENERATED_FILES list.  I have done it in this
order to avoid having some commits that could present the conflict but
don't have the check.

Change-Id: I109ba215b3e30debe82b711efb8826668fea0969
Approved-By: Kevin Buettner <kevinb@redhat.com>