gdb/testsuite/lib/gdb.exp: Fix core_find
A recent edit during a merge conflict resolution broke the core_find
method:

    Running [...]/gdb/testsuite/gdb.base/corefile.exp ...
    ERROR: tcl error sourcing [...]/gdb/testsuite/gdb.base/corefile.exp.
    ERROR: tcl error code TCL WRONGARGS
    ERROR: wrong # args: should be "core_find_1 coredir binfile arg output_file"
        while executing
    "$cb $tmpname {*}$args"
        (procedure "with_tmpdir" line 5)
        invoked from within
    "with_tmpdir coredir $deletefiles core_find_1 [list $binfile $arg  $output_file]"
        (procedure "core_find" line 2)
        invoked from within
    "core_find $binfile {}"
        (file "[...]/gdb/testsuite/gdb.base/corefile.exp" line 32)
        invoked from within
    "source [...]/gdb/testsuite/gdb.base/corefile.exp"
        ("uplevel" body line 1)
        invoked from within
    "uplevel #0 source [...]/gdb/testsuite/gdb.base/corefile.exp"
        invoked from within
    "catch "uplevel #0 source $test_file_name" msg"

The core_find passes the argumets to pass to core_find_1 in an explicit
list instead of having them directly as argument to with_tmpdir.  This
patch fixes this oversight.

Change-Id: Ibe6e31e76d52468ce0d664a0600db3ae35d10d23