gdb: fix build failure on armhf
armhf build fails because the implicit conversion operator from
rgb_color to `uint8_t *' introduces an ambiguity.

In ./gdb/tui/tui-io.c, expressions such as:

  init_color (next, rgb[0] * 1000 / 255, rgb[1] * 1000 / 255, ...

become ambiguous between:

  constexpr uint8_t& rgb_color::operator[](std::size_t)’
  operator[](uint8_t* {aka unsigned char*}, int) (built-in)

leading to a build error:

  error: ISO C++ says that these are ambiguous

Fix the issue by removing the unused implicit conversion operator.

Approved-By: Simon Marchi <simon.marchi@efficios.com>
Approved-By: Tom Tromey <tom@tromey.com>