[gdb/testsuite] Require allow_python_tests in gdb.cp/pretty-print.exp
I build gdb without python support, and ran into:
...
(gdb) source $src/gdb/testsuite/gdb.cp/pretty-print.py
$src/gdb/testsuite/gdb.cp/pretty-print.py:18: Error in sourced command file:
Undefined command: "import".  Try "help".
(gdb) ERROR: Undefined command "source $src/gdb/testsuite/gdb.cp/pretty-print.py".
...

Fix this by requiring allow_python_tests.