[gdb/testsuite] Remove lib/pdtrace.in
The test-case gdb.base/dtrace-probe.exp is written to test GDB's DTrace probe
support.

It uses a proc dtrace_build_usdt_test_program which is defined in
lib/dtrace.exp.

The proc defines the following fallback:
...
 # Note that if DTrace is not found in the host system then this
 # function uses the pdtrace implementation, which is located at
 # testsuite/lib/pdtrace.
 ...
 proc dtrace_build_usdt_test_program {} {
     ...
     # Make sure that dtrace is installed, it is the real one (not the
     # script installed by SystemTap, for example) and of the right
     # version (>= 0.4.0).  If it is not then use pdtrace instead.
     set dtrace "dtrace"
     set result [remote_exec host "$dtrace -V"]
     if {[lindex $result 0] != 0 \
	 || ![regexp {^dtrace: Sun D [0-9]\.[0-9]\.[0-9]} [lindex $result 1]]} {
	 set dtrace "${objdir}/lib/pdtrace"
     }
...

On my system, the fallback is activated, but then runs into trouble:
- warning: dtrace-probe-p.o: \
    missing .note.GNU-stack section implies executable stack
- error in dtrace-probe.o(.eh_frame); no .eh_frame_hdr table will be created
- undefined reference to `main'

I managed to fix the first two using:
- f_gen_asm '.section .note.GNU-stack,"",@progbits'
- additional_flags=-fno-asynchronous-unwind-tables
but the third seems to be caused by this bit:
...
    # Finally, we have to remove the __dtrace_* and __dtraceenabled_*
    # symbols from the object file, along with their respective
    # relocations.
    #
    # Note that the most obvious call:
    #   strip -v -N whatever -w foo.o
    # will not work:
    #   strip: not stripping symbol `whatever' because it is named in a relocation
    #
    # Fortunately using `-K !whatever' instead tricks strip to do the
    # right thing, but this is black magic and may eventually stop
    # working...
    $STRIP -K '!__dtrace_*' -w $objfile
    $STRIP -K '!__dtraceenabled_*' -w $objfile
...

This is meant to strip a few symbols, but it also strips away main, which it's
not supposed to do.

It's not clear to me how this is supposed to be done safely.

I tried out a few approaches using objcopy:
- using --strip-symbol
- using --redefine-sym
- using--remove-section=.rela.text
and only using the last one I managed to get an executable, but then ran into:
...
(gdb) info probes dtrace^M
No probes matched.^M
(gdb) FAIL: $exp: info probes dtrace
...

Given the amount of complexity present in the fallback, it is a bit
unfortunate that the test-case hasn't been setup from the start to exercise
the fallback always, also if a system version is available, and produce
a FAIL if it's failing but supposed to work.  That way we might have noticed
when the fallback broke (assuming it worked as expected from the start).

Anyway, given the "magic" comment I'm not putting more time into trying to
fix this, and since it makes no sense to maintain a broken script, I
propose to remove it.

Remove lib/pdtrace.in and related references.

I left a note at the point were we'd use the fallback, as a pointer in case
somebody wants to reinstate and fix it.

The test-case should still pass on a platform providing a system dtrace.
AFAICT from searching the web, Oracle Linux would be a good setup to try.

Tested on x86_64-linux.