[gdb/build] Fix Wunused-variable in selftests::test_enumerate
On openSUSE Leap 15.6, with gcc 7.5.0, I ran into:
...
enumerate-selftests.c: In function 'void selftests::test_enumerate()':
enumerate-selftests.c:85:22: error: \
  unused variable 'i' [-Werror=unused-variable]
     for (auto [i, val] : gdb::ranges::views::enumerate (vec))
                      ^
cc1plus: all warnings being treated as errors
...

Fix this by checking the value of i.

Tested on x86_64-linux.