sim/m32r: fix unused variable warning on non-Linux hosts
When building on macOS, I get:

    /Users/smarchi/src/binutils-gdb/sim/m32r/traps.c:191:18: error: unused variable 'cb' [-Werror,-Wunused-variable]
      191 |   host_callback *cb = STATE_CALLBACK (sd);
          |                  ^~

All the uses of `cb' in m32r_trap are inside the TRAP_LINUX_SYSCALL
case, which is guarded by `#ifdef __linux__'.  Move the declaration
inside that case, so that it only exists where it is used.

Change-Id: I609850daf7fa60d92856988dffe7e314eb1d8a30
Approved-By: Andrew Burgess <aburgess@redhat.com>