[gdb/build] Declare gdb_get_ncolors
Since a recent commit, I run into:
....
gdb/ui-style.c: In lambda function:
gdb/ui-style.c:597:20: error: ‘gdb_get_ncolors’ was not declared in this scope
  597 |       int colors = gdb_get_ncolors ();
      |                    ^~~~~~~~~~~~~~~
make: *** [Makefile:2096: ui-style.o] Error 1
....

Fix this by adding the missing declaration.

(cherry picked from commit 93172549b7397c526b3622e16484909028d81e41)
Change-Id: I121cce5f624599a3c68138f218d0b1df2d4e50a7