Don't include infrun.h in gdbarch.h
A following patch will want to include gdbarch.h in gdbthread.h.  That
won't work without this patch, though, because it trips on header
recursion:

  $ make thread.o
    CXX    thread.o
  In file included from ../../src/gdb/infrun.h:21,
		   from ../../src/gdb/gdbarch.h:32,
		   from ../../src/gdb/breakpoint.h:38,
		   from ../../src/gdb/inferior.h:40,
		   from ../../src/gdb/thread.c:25:
  ../../src/gdb/gdbthread.h:158:3: error: ‘bpstat’ does not name a type; did you mean ‘lstat’?
    158 |   bpstat stop_bpstat = nullptr;
	|   ^~~~~~
	|   lstat

  (...)

AFAICT, gdbarch.h doesn't need to include infrun.h at all, so fix it
that way.

This commmand can be used to confirm that the headers are
self-contained:

 $ make check-headers CHECK_HEADERS="gdbarch.h infrun.h gdbthread.h"
 (no errors)

Change-Id: I47ec1f348f6e751a5fe54e00b5cf8cbf8dc1a9f7