gdb/amd-dbgapi: fix -Wdeprecated-enum-enum-conversion warning
With gcc 16, I get:

    /home/smarchi/src/binutils-gdb/gdb/amd-dbgapi-target.c: In function ‘void info_dispatches_command(const char*, int)’:
    /home/smarchi/src/binutils-gdb/gdb/amd-dbgapi-target.c:4729:26: error: bitwise operation between different enumeration types ‘amd_dbgapi_dispatch_barrier_t’ and ‘amd_dbgapi_dispatch_fence_scope_t’ is deprecated [-Werror=deprecated-enum-enum-conversion]
     4729 |             if ((barrier | acquire) && release)
          |                  ~~~~~~~~^~~~~~~~~

IIUC, the intent of this is just to know if we've written something in `ss`
already, and if we're going to write more.  And if so, write a `|`
separator.  The `|` should probably have been a `||`, or because we like
to be explicit in GDB:

    if ((barrier != AMD_DBGAPI_DISPATCH_BARRIER_NONE
         || acquire != AMD_DBGAPI_DISPATCH_FENCE_SCOPE_NONE)
        && release != AMD_DBGAPI_DISPATCH_FENCE_SCOPE_NONE)
      ss << "|";

But I think it's simpler to rewrite this to append to a string, and
append a `|` if we're about to append something and the string is not
empty.  A stringstream has no advantage over using a string in this
case.

Change-Id: I48307186f00a9943f6be388960c85ce53d10b0c3
(cherry picked from commit 115bea6215f39fd93abba206547389e1604b2706)