gdbsupport: remove iteration_status_str
When building with g++ 8 (on Alma Linux 8), we get:

      CXX    ada-exp.o
    In file included from /binutils-gdb/gdb/../gdbsupport/array-view.h:24,
                     from /binutils-gdb/gdb/../gdbsupport/common-utils.h:27,
                     from /binutils-gdb/gdb/../gdbsupport/common-defs.h:214,
                     from /binutils-gdb/gdb/defs.h:26,
                     from <command-line>:
    /binutils-gdb/gdb/../gdbsupport/iteration-status.h: In function ‘constexpr const char* iteration_status_str(iteration_status)’:
    /binutils-gdb/gdb/../gdbsupport/gdb_assert.h:43:22: error: call to non-‘constexpr’ function ‘void internal_error_loc(const char*, int, const char*, ...)’
       internal_error_loc (__FILE__, __LINE__, _("%s: " message), __func__, \
       ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             ##__VA_ARGS__)
             ~~~~~~~~~~~~~~
    /binutils-gdb/gdb/../gdbsupport/iteration-status.h:45:3: note: in expansion of macro ‘gdb_assert_not_reached’
       gdb_assert_not_reached ("invalid iteration_status value");
       ^~~~~~~~~~~~~~~~~~~~~~

It turns out that iteration_status_str isn't used, it apparently was
only used transiently in my series.  Remove it to fix the build failure.

Change-Id: Icb43d4d719ad94a3eafa5fd55c81a56cbe0da91d